-- AlterEnum
ALTER TYPE "EmailType" ADD VALUE 'USER_ASSIGNED_TO_COHORT';
ALTER TYPE "EmailType" ADD VALUE 'USER_GRADUATED';
ALTER TYPE "EmailType" ADD VALUE 'USER_REMOVED_FROM_COHORT';
ALTER TYPE "EmailType" ADD VALUE 'USER_SUSPENDED';
